In [173]:
import pandas as pd
import xlrd
import re
attacks = pd.read_excel('C:/Users/Data Analyst/Documents/Otros/sharks.xlsx')
df = attacks
df.drop_duplicates()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
0,2018.06.25,43276,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303
1,2018.06.18,43269,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,...,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302
2,2018.06.09,43260,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301
3,2018.06.08,43259,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300
4,2018.06.04,43255,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6304,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6306
6305,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6307
6306,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6308
6307,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6309
6308,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6310

In [193]:
df.drop([6302,6303,6304,6305,6306,6307,6308], inplace = True)

In [178]:
for i in df:
    df[i].fillna('Unknown', inplace = True)

In [179]:
df.Date = df.Date.str.replace(r'\bReported','')
df.Date = df.Date.str.replace(r'\bAfter','')
df.Date = df.Date.str.replace(r'\bBetween','')
df.Date = df.Date.str.replace(r'\bBefore','')
df.Date = df.Date.str.replace(r'\bSummer','')
df.Date = df.Date.str.replace(r'\bEarly','')
df.Date = df.Date.str.lstrip()

In [180]:
df.columns = df.columns.str.lstrip()
df.columns = df.columns.str.rstrip()

In [152]:
df['Date'] = pd.to_datetime(df['Date'], format='%d/%B/%Y', errors = 'coerce')
print(set(df.Date))

In [181]:
df.drop(df.loc[df['Type']=='Unknown'].index, inplace=True)
df.Type.value_counts()

Unprovoked      4595
Provoked         574
Invalid          547
Sea Disaster     239
Boating          203
Boat             137
Questionable       2
Boatomg            1
Name: Type, dtype: int64

In [188]:
countries = ['USA', 'AUSTRALIA', 'SOUTH AFRICA','PAPUA NEW GUINEA', 'NEW ZELAND', 'BRAZIL', 'BAHAMAS', 'MEXICO', 'ITALY', 'FIJI','PILIPPINES', 'REUNION', 'NEW  CALEDONIA', 'CUBA' 'MOZAMBIQUE', 'ENGLAND']
df.Country = [df.drop(df.loc[df.Country[i]].index, inplace=True) for i in df.Country if i not in countries]

In [190]:
df.Name[df.Name.str.startswith('mal')]  ='Unknown'
df.Name[df.Name.str.startswith('fema')] = 'Unknown'
df.drop(df.loc[df['Name']=='Unknown'].index, inplace=True)

C:\Users\Data Analyst\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\Data Analyst\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [218]:
j = df.Species.value_counts()
j.head(50)

White shark                                           157
Shark involvement prior to death was not confirmed     74
Tiger shark                                            66
Shark involvement not confirmed                        63
Bull shark                                             44
Shark involvement prior to death unconfirmed           40
6' shark                                               37
1.8 m [6'] shark                                       34
4' shark                                               34
1.5 m [5'] shark                                       28
3' shark                                               26
1.2 m [4'] shark                                       25
5' shark                                               23
Questionable incident                                  23
4' to 5' shark                                         22
Wobbegong shark                                        21
3 m [10'] shark                                        21
2 m shark                                              20
No shark involvement                                   17
2.4 m [8'] shark                                       16
12' shark                                              15
3 m shark                                              15
3.7 m [12'] shark                                      14
1.2 m to 1.5 m [4' to 5'] shark                        14
3' to 4' shark                                         13
Blacktip shark                                         13
1.5 m shark                                            12
5 m [16.5'] white shark                                12
10' shark                                              12
"a small shark"                                        12
6 m [20'] white shark                                  12
Bronze whaler shark                                    11
Zambesi shark                                          11
Raggedtooth shark                                      11
4 m [13'] white shark                                  10
Grey nurse shark                                       10
7' shark                                               10
Blue shark                                             10
Shark involvement prior to death not confirmed          9
2.1 m [7'] shark                                        9
Mako shark                                              9
Hammerhead shark                                        9
"small shark"                                           8
a small shark                                           8
White shark, 4 m [13']                                  8
Nurse shark                                             8
3 m [10'] white shark                                   8
1.8 m shark                                             7
1 m shark                                               7
2' to 3' shark                                          7
Name: Species, dtype: int64

In [ ]:
df.drop(df.loc[df['Species']=='Invalid'].index, inplace=True)
df.drop(df.loc[df['Species']=='Questionable'].index, inplace=True)
df1 = df[df['Species'].str.contains('white') | df['Species'].str.contains('tiger') |
         df['Species'].str.contains('lemon')|df['Species'].str.contains('Tiger')|
       df['Species'].str.contains('White')|df['Species'].str.contains('tiger')|
        df['Species'].str.contains('Zambesi')|df['Species'].str.contains('Hammerhead')|
        df['Species'].str.contains('Nurse')|df['Species'].str.contains('nurse')|
        df['Species'].str.contains('Whaler')| df['Species'].str.contains('bull')|
        df['Species'].str.contains('Bull')|df['Species'].str.contains('Lemon')|
        df['Species'].str.contains('blue')|df['Species'].str.contains('Blue')|
        df['Species'].str.contains('spinner')|df['Species'].str.contains('Spinner')|
        df['Species'].str.contains('blacktip')| df['Species'].str.contains('Bronze')|
        df['Species'].str.contains('Mako')|df['Species'].str.contains('Raggedtooth')|
        df['Species'].str.contains('Wobbegong') |df['Species'].str.contains('mako') |
         df['Species'].str.contains('Blacktip') |df['Species'].str.contains('Spinner')
        
        ]